package model

import "time"

type Todo struct {
	ID          int       `json:"id"`  //Generated by the server; clients should not provide it when creating a todo.
	Title       string    `json:"title"`  //Required; should not be empty.
	Description string    `json:"description"` //Optional (or required if your project later specifies it).
	Completed   bool      `json:"completed"`  //Defaults to false when a todo is created.
	CreatedAt   time.Time `json:"createdAt"`  //Set automatically by the server.
	UpdatedAt   time.Time `json:"updatedAt"`  //Set automatically by the server and updated whenever the todo changes.
}